### ISSUE TITLE
include Brazil NTv2 grid shift files

### ISSUE THREAD

**Issue by jmckenna** [OSGeo/proj-datumgrid#101]
- See discussion in QGIS-Brazil forum: https://groups.google.com/d/msg/qgisbrasil/zdNGyfnoxKg/9a8xpU_2CQAJ

- Grid files provided by Brazil's national mapping agency, IBGE : ftp://geoftp.ibge.gov.br/informacoes_sobre_posicionamento_geodesico/sirgas/aplicativos/transformacao_coordenadas/progrid_compacto.zip

- Note that the archive seems to be for a 'ProGrid' software, but the grid files live in the archive at /ProGriD_compacto/program files/Progrid/GridFiles

- here are those 4 grid files: [brazil-grids.zip](https://github.com/OSGeo/proj-datumgrid/files/4020959/brazil-grids.zip)

- I am unsure of the exact license : there is however a licence file for 'ProGrid', in Portuguese [ProgridLic.pdf](https://github.com/OSGeo/proj-datumgrid/files/4020964/ProgridLic.pdf)

Will try to get others from QGIS-Brazil to join this ticket discussion...

**Comment by rouault** [comment]
Thanks Jeff. I have been contacted a few days ago by someone at IBGE. They're working at the licensing of the grids (the current license for ProGrid is inappropriate for us)

**Comment by yjmenezes** [comment]
Hi,

I wrote to IBGE agency too, asking about NTV2 grid data license and suggesting a PROJ4 compatible, at least  for the grid data files.

**Comment by yjmenezes** [comment]
Hi

I got an answer from IBGE team today:

"""
Regarding the ProGriD NTv2 data licensing suggestion in an open license, I inform you that we are evaluating and will inform users as soon as possible.
"""

**Comment by rouault** [comment]
@yjmenezes I got the same feedback from the person at IBGE I'm interacting with. Maybe in order not to make them feel "harassed" by us, let me follow up with them for now. If I don't get results (she mentionned dealing with that at her return from vacations beginning of February), I'll pass the torch back to you.

**Comment by yjmenezes** [comment]
@rouault  ,  I agree with you, for sure IBGE will go release the grid data under an open license. I will be watching here. Thank you and all Proj team.

**Comment by rouault** [comment]
WARNING: This repository is no longer open for adding new datasets. Starting with PROJ 7, the [PROJ-data](https://github.com/OSGeo/PROJ-data) repository is the new home for PROJ datasets.

Go to its [CONTRIBUTING](https://github.com/OSGeo/PROJ-data/blob/master/CONTRIBUTING.md) instructions

**Comment by rouault** [comment]
@yjmenezes Is there someone in the Brazilian community willing to take the relay ? I don't manage to get to the desired conclusion with my contact at IBGE. She mentionned Jorge Gustavo Rocha from Minho University as someone else who already contacted them to get an open license for the grids. Whoever want to take the relay on this, please email me at even.rouault at spatialys.com and I'll forward you all the email exchanges I had, and try to "brief" you on the important points from my perspective.

**Comment by rouault** [comment]
ah and she also mentionned you @yjmenezes
