### ISSUE TITLE
Clearer instructions on how to download and include all grids 

### ISSUE THREAD

**Issue by alpha-beta-soup** [OSGeo/proj-datumgrid#108]
(Let me preface this by saying that I'm aware of [PROJ-data](https://github.com/OSGeo/PROJ-data) for PROJ 7, but I'm trying to use PROJ 6.)

The instructions seem to only be:

> The files in this package can be unpacked in the PROJ data directory. For an installed PROJ this may be /usr/local/share/proj or /usr/share/proj on unix style operating systems.

What is the recommended way of doing this if I want all grids? The options would seem to be:
- git clone with Git LFS
- wget/curl some compressed distribution
- install using a package manager

In the first case, once I've cloned, which files would I need to copy to the Proj data directory? Do I need to run Make as well?

In the second case, what is the URL to use?

If the third case is an option, the documentation doesn't make that clear.

--- 

What I expected the documentation to say:

> To install all grids, you need to download all the grids and unpack them to the PROJ data directory:
> `wget https://example.com/proj-grids.zip -p /tmp/ && unzip /tmp/proj-grids.zip && mv /tmp/proj-grids $PROJ_DATA_DIR`

i.e. a clear command to actually obtain and install the grids. At the moment the instructions are very vague, and other online documentation is confused since we're at the transition between v6 and v7.

---

What I'm doing:

```dockerfile
RUN curl -L --output /tmp/proj-datumgrid-oceania-1.2.zip https://github.com/OSGeo/proj-datumgrid/releases/download/oceania-1.2/proj-datumgrid-oceania-1.2.zip \
&& unzip /tmp/proj-datumgrid-oceania-1.2.zip -d /usr/local/share/proj \
&& curl -L --output /tmp/proj-datumgrid-north-america-1.4.zip https://github.com/OSGeo/proj-datumgrid/releases/download/north-america-1.4/proj-datumgrid-north-america-1.4.zip \
&& unzip /tmp/proj-datumgrid-north-america-1.4.zip -d /usr/local/share/proj \
&& curl -L --output /tmp/proj-datumgrid-europe-1.6.zip https://github.com/OSGeo/proj-datumgrid/releases/download/europe-1.6/proj-datumgrid-europe-1.6.zip \
&& unzip /tmp/proj-datumgrid-europe-1.6.zip -d /usr/local/share/proj \
&& curl -L --output /tmp/proj-datumgrid-world-1.0.zip https://github.com/OSGeo/proj-datumgrid/releases/download/world-1.0/proj-datumgrid-world-1.0.zip \
&& unzip /tmp/proj-datumgrid-world-1.0.zip -d /usr/local/share/proj
```
It would be nice if this was documented clearly. (And, as an aside, distrubuted like `all-latest` rather than per-region and per-version.)

**Comment by sebastic** [comment]
> In the second case, what is the URL to use?

See: https://proj.org/download.html#download

Because proj-datumgrid is deprecated in favour of proj-data, don't expect any changes for proj-datumgrid.

**Comment by rouault** [comment]
Yes, we are not going to document PROJ 6 behaviour now that PROJ 7 is released. Basically your above snippet is the recommended way, in case someone else find this issue.
