### ISSUE TITLE
Remove Australia GDA94 -> GDA2020 grids

### ISSUE THREAD

**Issue by sebastic** [OSGeo/proj-datumgrid#16]
We're refusing to eat our own dogfood (https://github.com/OSGeo/proj.4/pull/822) because the size of proj-datumgrids-1.7RC1 is considered "just a waste of time and bandwith to download that.".

Removal of the GDA grids (added via #3) reduces the size of the archive significantly.

Perhaps we should only consider including grids of reasonable size (e.g. < 5 MB).

CC: @nyalldawson

**Comment by nyalldawson** [comment]
Well - as an Australian and someone whose livelihood depends on opensource software having proper support for Australian projections and datums this is rather disappointing! 

Couldn't OSGeo/proj.4#822 be solved in an alternate way by just direct downloading specific grids vs restricting this package?

I agree that it's unfortunate that the grids are so large, but they are very very important for Australia...

**Comment by nyalldawson** [comment]
Actually looking at OSGeo/proj.4#822 it seems that the original approach was to directly download the relevant grid only.

**Comment by kbevers** [comment]
I wrote this on the other PR:

> 
> I understand where you are coming from and in principle I agree. The thing is though, there's a difference between users that download the package once and an automated system downloading the package several of a hundred times a day (there's 15 test targets that all need the package, that's ~1.5GB pr commit). It takes extra time to download the package, but more importantly it wastes bandwith for both OSGeo and the CI providers. We get all of this for free and I don't want to abuse that privilige unless it is necessary. It isn't in this case. So for now i prefer to download what's needed for the tests to run and not much else.
> 
> I believe it should be possible to do caching of frequently downloaded files. When I have some more time on my hands I will look into that as a part of a more thorough overhaul of the test-suite.

**Comment by kbevers** [comment]
There's no need to dramatise this. It's purely a practical problem with a simple solution.

**Comment by sebastic** [comment]
https://github.com/OSGeo/proj.4/pull/822 only concerns Travis, the size of proj-datumgrid affects all users.

The significantly increased size also affects the Debian package where creating the source package takes significantly more time for example.

The proj-data package (which provides `/usr/share/proj`) is installed on every system which has libproj installed, and via GDAL and other popular packages that depend on libproj, this affects over 10% of the Debian user base.

**Comment by kbevers** [comment]
> #822 only concerns Travis, the size of proj-datumgrid affects all users.

It should also be extended to include Appveyour if merged.

> The significantly increased size also affects the Debian package where creating the source package takes significantly more time for example.

> The proj-data package (which provides /usr/share/proj) is installed on every system which has libproj installed, and via GDAL and other popular packages that depend on libproj, this affects over 10% of the Debian user base.

I am not happy about that either. That is why I suggested #7. So that users can download what they need instead of everything. I have no use for the Australian grids, but coming from a national geodetic service myself see the value in having them readily available. The situation is not ideal at the moment but we can change that in the future. Let's take a step back and delay this issue to after PROJ 5.0.0 and come up with a proper solution that meets all our various needs.

**Comment by sebastic** [comment]
@nyalldawson do you build proj yourself for your work or do you rely on distribution packages?

If the Australian grids are split off into their own package (e.g. proj-datumgrid-australia), Travis won't be using those grids by default any more, and the Debian package will most likely also not included them by default any more (because any grid that is not required for the proj test suite doesn't need to be part of the proj package). proj-datumgrid-australia will need to be packaged separately.

**Comment by kbevers** [comment]
> proj-datumgrid-australia will need to be packaged separately.

I think this is the reasonable thing to do. It's been like that in the OSGeo4W distribution for some time (other grids than the aussie ones, thoguh) and that seem to have been succesfull. Users will have to engage their brains a little to figure out that somethings missing but the word will quickly catch on I am sure.

**Comment by sebastic** [comment]
@kbevers what are your thoughts about only including grids of reasonable size?

**Comment by kbevers** [comment]
> @kbevers what are your thoughts about only including grids of reasonable size?

Well, we'd have to define what a "reasonable size" is. Of course anything <1MB is reasonable. Is the 80MB grids from Australia reasonable? Perhaps. I haven't looked into why they have the size that they do. It might be that they are totally oversampled, in which case I think they are unreasonably large. It might also be because the country is huge and that the legacy reference frames has build up so much tension that a finely meshed grid is the only way to create a mapping from the legacy systems to GDA2020, in which case I think the size is reasonable. Justified might be a better word. We should ask the ICMS guys about that. 

I clearly was too quick to merge this. I didn't realize the impact of those big files at the time and should have investigated a bit further. At least to see if there is something to be done about the grid sizes.

I hope we can agree on a solution that meets everyone's needs. @sebastic How big a burden is it for you to set up let's say 5 or 6 regional grid packages for Debian? To go along with the current package, that is.

**Comment by sebastic** [comment]
In my view proj-datumgrid should remain the core archive which includes all the grids required for the proj testsuite, it is also the content that will be included in the proj-data package in Debian.

I'm very much in favor of splitting out large grids and other national grids that are not required for the proj test suite. The Debian package has included in the Swiss grid since before my time because of user demand, this is a separate shar archive in the Debian package alongside the proj-datumgrids archive. This can be extended for other countries, but for countries with large grids this should be a separate Debian source package.

If there is sufficient user demand to have non-core grids easily installed on Debian and derivatives, they can be packaged separately. I'm not very fond of creating and maintaining packages which I don't use myself, but because there is pretty much no one else to do the work in Debian most of the packages I maintain I don't actually use myself. Ideally users who have a need for specific packages step up and contribute to maintaining the package, but in practice this mostly doesn't happen.

Hence my question to @nyalldawson, if he relies on the proj-data package for grids on Debian or derivatives (most GIS people tend to use Ubuntu) I'd be willing to package the Australian grids. As I've also packaged the (non-free) Dutch grids mostly for benefit of the community, I don't use it myself other than as another test case for proj (the mandatory tests of the Dutch grids has uncovered issues in proj in more than one occasion).

I'm currently looking into generating multiple source packages for proj-datumgrid, but it looks like CPack doesn't support creating multiple source packages (only binary packages via install components). So the build system will likely need to be reimplemented with Autotools.

**Comment by kbevers** [comment]
I think it is valuable to have a shared collection of all the grids that are freely available. We can make that happen here. We can also help make it easier for packagers across various systems by preparing a set of zip-archives that mostly fit all users needs. From the discussion I seems to me that we can all agree on this.

Here's my proposal. We create the following packages:

1.  `proj-datumgrids-minimal-x.y.zip` which contain basically the `proj-datumgrids-1.6.zip` files, `BETA2007.gsb` and `egm96_15.gtx`. This should be enough for the tests to pass and deliver the absolute minimum necessary ressources needed for PROJ to work correctly. Packagers can use this when updating existing datumgrids packages.
2. `proj-datumgrids-REGION-x.y.zip` which contain grids valid in `REGION` that is not already included in the `minimal` archive. At the moment we would probably only need `EUROPE` and `OCEANIA` distributions, but this can obviously be expanded when necessary.

Existing datumgrid packages can continue using the `minimal` distribution. If someone needs it they can create new packages for their own region based on the archives we prepare here. I think this provides the most smooth transition to a more divided distribution. IT would also be possible to create a meta-package that include all available grids by combining both the `minimal` and `REGION` grids. Is this an acceptable way forwards?

> I'm currently looking into generating multiple source packages for proj-datumgrid, but it looks like CPack doesn't support creating multiple source packages (only binary packages via install components). So the build system will likely need to be reimplemented with Autotools.

If this is too much work at the moment I can prepare the various zip-archives manually this time around.

**Comment by sebastic** [comment]
I don't like the `-minimal` name, the content of the archive is still pretty much the same as previous `proj-datumgrid` archives so I think it should keep the name.

In addition to the `proj-datumgrid` archives we provide the `proj-datumgrids-<REGION>` archives.

Packagers can keep including the `proj-datumgrid` archive and only need to update the version, they can chose to also include or package separately the additional region archives.

**Comment by kbevers** [comment]
Scratch the `-minimal` - it's not important to me. Let's go this way. I see that you found a CPack solution for the regional packages as well. Good. I have to leave the computer for a few hours but I am keen to continue working on this when I am back again.

**Comment by nyalldawson** [comment]
I understand the difficulties here. Personally, I'm fine for a split package - my main goal is that the Australian grids are included in osgeo4w and installed alongside proj by default, so that a typical osgeo4w install has the grids ready to go without the need for additional user installs. But I can bring that up with the osgeo4w team...

**Comment by sebastic** [comment]
#17 has been merged, there is no need to remove the Australian grids any more, a separate archive (`proj-datumgrid-oceania`) is used instead.

**Comment by nyalldawson** [comment]
Thanks @kbevers ! I'm going to see if the grids can't be thinned to allow their inclusion back in the base package. See https://github.com/icsm-au/transformation_grids/issues/4

**Comment by alexgleith** [comment]
Hey folks, I've mentioned this to the folks who look after the grids, thanks @nyalldawson for linking us in to this.

I'll just say that the Australian grids were prepared very carefully, and I would assume that they are not oversampled and that the resolution that they are at is appropriate to capture the best precision of the difference between datums.

With an utopian view, there might be a way to vectorise these and still capture the same amount of information with less data, but that's probably not realistic. 

It would be great if the non-technical user of a package like QGIS just got the best transformations by default, like Nyall says. And it would be great if folks who are not in Australia didn't need to have the large files too... Not sure how to achieve it. Thank you all for working on it though!

**Comment by kbevers** [comment]
@nyalldawson Just so it's clear: I absolutely think that it is reasonable for a big application such as QGIS to include these grids by default. QGIS is not the only user of PROJ though. There are many cases where including every grid we know of would be impractical or even impossible (think embedded systems). QGIS should be able to get around the split packages by simply stating those as requirements for QGIS. I don't think that is unreasonable at all. And at the same time it lets other software packages be a bit more specific in what extranous ressource it might want to benefit from. Is that a usable solution for you?

@alexgleith Thanks for pitching in. I think you guys have done the right thing with the grids. They might be big but that is bound to happen in a big country when trying to map legacy reference frames to modern frames.  You could probably do the transformation as a polynomium mapping but that would just be a pain in the ass in so many other ways.

**Comment by andrewharvey** [comment]
> If there is sufficient user demand to have non-core grids easily installed on Debian and derivatives, they can be packaged separately.

:+1: vote for demand for the Australian grids easily installed on Debian. As a very active user of your Debian packaging work @sebastic I'm very appreciative.

> I'm not very fond of creating and maintaining packages which I don't use myself, but because there is pretty much no one else to do the work in Debian most of the packages I maintain I don't actually use myself.

I've tried to help out in the past and can say things like the recent move to GitLab are most welcome. I'm much more likely to help out if I can just submit a merge request and have GitLab CI do automated testing and building, eve more so if bugs are moved to GitLab issues.

**Comment by sebastic** [comment]
Please file a [RFP](https://wiki.debian.org/RFP) bugreport requesting a package for proj-datumgrids-oceania and make sure to add `debian-gis@lists.debian.org` to the [CC](https://www.debian.org/Bugs/Reporting#xcc).

GitLab issues will never be used for packages maintained by the Debian GIS team, we have a dedicated bugtracker already.
