### ISSUE TITLE
Include vdatum grids?

### ISSUE THREAD

**Issue by sebastic** [OSGeo/proj-datumgrid#2]
http://download.osgeo.org/proj/vdatum/ provides various grids that are used in the gie test suite for example (https://github.com/OSGeo/proj.4/issues/769). Not having these grids available during the build of proj (5.0.0-rc1) causes the tests to fail.

These grids should probably be included in proj-datumgrid (if their licensing allows it) to not require manual download of these like in the [proj Dockerfile](https://github.com/OSGeo/proj.4/blob/master/Dockerfile). Such a process is not appropriate for packagers of proj.

None of the vdatum grids state the terms for their distribution, so including them as-is in proj-datumgrid is problematic.

**Comment by kbevers** [comment]
The only grid in the test suite not covered here is `egm96_15.gtx`. I think that would be absolutely reasonable to include that here.

**Comment by sebastic** [comment]
http://earth-info.nga.mil/GandG/wgs84/gravitymod/egm96/binary/binarygeoid.html does not state a license, so I've contacted wgs84@nga.mil asking for clarification.

If it's public-domain, including it in proj-datumgrid should be fine.

**Comment by kbevers** [comment]
Any response from NGA?

**Comment by sebastic** [comment]
No(t yet).

**Comment by hobu** [comment]
As far as I know VDATUM software and all related data is public domain. Has there ever been a case where it hasn't been? I can't think of one.

**Comment by kbevers** [comment]
I am sure that's correct, but it is not obvious from the available documentation. At least I haven't been able to find it. It would be nice to be able to reference a license for each grid we include.

**Comment by sebastic** [comment]
Since the vdatum is produced by the US government agency, I think it's safe to assume it's in the public domain.

Documenting it as such will allows us to continue (as mentioned in #17) until we hear otherwise.

**Comment by rouault** [comment]
Closing. This has been resolved. We have now a good set of vdatum grids
