### ISSUE TITLE
Include OSTN02_NTv2.gsb and OSTN15 (Great Britain)

### ISSUE THREAD

**Issue by don-vip** [OSGeo/proj-datumgrid#21]
Hello,
While looking at https://github.com/OSGeo/proj.4/issues/904 I noticed the ESRI file uses 102 times the NTv2 grid "OSTN02_NTv2.gsb".
I found it [here](https://www.ordnancesurvey.co.uk/business-and-government/help-and-support/navigation-technology/os-net/ostn02-ntv2-format.html).
The license seems OK:
```
The OSTN02 data in NTv2 format is licensed to users pursuant to the terms of the Open Source Initiative BSD Licence (see the opensource bsd license page).

The copyright notice which must be attached to the software under the terms of the BSD licence is as follows:

'© Crown copyright, Ordnance Survey and the Ministry of Defence (MOD) 2002. All rights reserved.
```
Should it be included in this package?

**Comment by sebastic** [comment]
Probably yes, along with the init files that reference those grids as suggested by @kbevers in https://github.com/OSGeo/proj.4/issues/904#issuecomment-376822881.

**Comment by SilverSloth** [comment]
OSTN02 was replaced by OSTN15 in around 2016. The Esri file is outdated.

 The new file can be found here: https://www.ordnancesurvey.co.uk/business-and-government/help-and-support/navigation-technology/os-net/formats-for-developers.html
Here they supply NTV2 files both from and to ETRS89.
