### ISSUE TITLE
Include BWTA2017.gsb (Baden-Württemberg)

### ISSUE THREAD

**Issue by m-kuhn** [OSGeo/proj-datumgrid#22]
There is a [BWTA2017.gsb](https://www.lgl-bw.de/lgl-internet/web/sites/default/de/05_Geoinformation/Galerien/Dokumente/BWTA2017.zip) for Baden-Württemberg available [from the Landesamt für Geoinformation](https://www.lgl-bw.de/lgl-internet/opencms/de/05_Geoinformation/Liegenschaftskataster/ETRS89-UTM/) 

The license looks good

> Hinweis: Die NTv2-Dateien BWTA2017 sind Open Data nach der "Datenlizenz Deutschland – Namensnennung – Version 2.0". Details unter https://www.govdata.de/dl-de/by-2-0.
Bezeichnung des Bereitstellers: "Datengrundlage: LGL, www.lgl-bw.de".
Verweis auf den Datensatz (URL): https://www.lgl-bw.de/lgl-internet/opencms/de/05_Geoinformation/Galerien/Dokumente/BWTA2017.zip

Note: the unzipped file is 375MB big

Should this be included in this package?

**Comment by sebastic** [comment]
Due to the large size it should be included in proj-datumgrid-europe.

Are there English language pages for the license and related information?

**Comment by m-kuhn** [comment]
> Due to the large size it should be included in proj-datumgrid-europe.

That is the subdirectory europe in this repository?

> Are there English language pages for the license and related information?

Yes, the following quote is from https://www.govdata.de/dl-de/by-2-0

>  Data licence Germany – attribution – version 2.0
> 
> (1) Any use will be permitted provided it fulfils the requirements of this "Data licence Germany – attribution – Version 2.0".
> 
> The data and meta-data provided may, for commercial and non-commercial use, in particular
> 
>    * be copied, printed, presented, altered, processed and transmitted to third parties;
>    * be merged with own data and with the data of others and be combined to form new and independent datasets;
>    * be integrated in internal and external business processes, products and applications in public and non-public electronic networks.
> 
> (2) The user must ensure that the source note contains the following information:
> 
>    * the name of the provider,
>    * the annotation "Data licence Germany – attribution – Version 2.0" or "dl-de/by-2-0" referring to the licence text available at www.govdata.de/dl-de/by-2-0, and
>    * a reference to the dataset (URI).
> 
> This applies only if the entity keeping the data provides the pieces of information 1-3 for the source note.
> 
> (3) Changes, editing, new designs or other amendments must be marked as such in the source note.

**Comment by sebastic** [comment]
> That is the subdirectory europe in this repository?

Yes. For backgrounds, see: #16 and the related issues.

Regarding the license, it's a shame they had to invent their own license instead of using a well known license. At first glance is looks compatible with the [OSD](https://opensource.org/osd-annotated) & [DFSG](https://www.debian.org/social_contract#guidelines), but the license places some restrictions which are stricter than the BSD licenses which these terms resemble. This may not be compatible with the OSD & DFSG.

The second clause is a bit weird, who is "The user" and who is "the entity keeping the data"? It's unclear to whom the restrictions apply, the clause seems to imply that the user must only ensure the source notice contains the required information if the provider of the data supplied that information in the first place.

The requirements from the third clause are also stricter than the attribution requirements from the BSD licenses, and may not be compatible with paragraph 4 of the OSD & DFSG (Integrity of The Author's Source Code).

Because the license is not clearly compatible with the OSD & DFSG, I'm hesitant to recommend the inclusion of this grid in the proj-datumgrid-europe distribution.

**Comment by thbaumann** [comment]
I just called our contact person at the Landesamt für Geoinformation (LGL, lgl-bw.de) and emailed him to ask what's the LGL's point of view concerning this issue

**Comment by thbaumann** [comment]
Here is the answer of the LGL which says mor or less that in their understanding it's ok to include the BWTA grid in QGIS:

Sehr geehrter Herr Baumann,
 
nach unserem Verständnis können Sie das Gitter in QGIS implementieren. Da sollte auch unsere Lizenzierung Datenlizenz Deutschland - Namensnennung - Version 2.0 kein Hindernis sein.
 
Die Open Data Lizenz nach Datenlizenz Deutschland - Namensnennung - Version 2.0 wurde in übergeordneten Gremien so bestimmt und sind uns vorgegeben.
Wir selbst können und wollen daher an einer Diskussion, bzw. Lizenzvergleiche mit  OSD & DFSG – Lizenzsierungen nicht teilnehmen.
 
Viele Grüße
i.A. Klaus Hermann, LGL Baden-Württemberg

--
( My main question was:
 "Eine noch offene Frage ist, ob die Datei selbst (BWTA2017.gsb) auch von der Lizenz her mitausgeliefert werden dürfte oder ob der Nutzer diese sich selbst runterladen muss.")

**Comment by kbevers** [comment]
My German is a bit rusty, but it seems to me that their intentions are in the right place but they unfortunately decided to write their own license which is not completely in line with what they wanted in the first place. The last line:

> Wir selbst können und wollen daher an einer Diskussion, bzw. Lizenzvergleiche mit OSD & DFSG – Lizenzsierungen nicht teilnehmen.

does that mean that they are looking into a change in their license?

**Comment by sebastic** [comment]
According to the Google Translation it seems that they were given the license by others higher in the chain of authority and are not in a position to discuss license compatibility.

**Comment by kbevers** [comment]
Okay, that was quite different than my interpretation. I should have paid more attention in my German lessons!

What do you say @sebastic, can we include this or not?

**Comment by sebastic** [comment]
Since LGL is not the party to discuss license issues with, I suggest to not include the grid until the license issues can be clarified by a party who is qualified/authorized to speak on those subjects.

Better safe than sorry, we don't know for sure what obligations users/recipients of the proj-datumgrid distribution get themselves into when this grind is included.

We can link to the grid in the resource files documentation and also link to this issue for the backgrounds regarding the license uncertainties.

**Comment by m-kuhn** [comment]
@rdbath can you ask for an official contact regarding this?

**Comment by thbaumann** [comment]
@m-kuhn : done. wating for an answer

**Comment by thbaumann** [comment]
Here's the answer of the LGL:

> Sehr
> 
>  geehrter Herr Baumann,
>  
> wir haben hier keine konkreten Ansprechpartner.
> 
> Es gibt es aber Möglichkeiten zur Kontaktaufnahme: https://www.govdata.de 
> Datenlizenz Deutschland: https://www.govdata.de/web/guest/lizenzen 
>  
> 
> Viele Grüße
> i.A. Klaus Hermann, LGL Baden-Württemberg

So they do not know an official contact but gave us the (already known) url https://www.govdata.de of the "Geschäfts- und Koordinierungsstelle GovData" (which also has a twitter account https://twitter.com/govdata_de )
I just tweeted them to ask who's the contactperson for questions concerning the licence.

**Comment by thbaumann** [comment]
so here's the answer: The BMI (https://www.bmi.bund.de) is responsible for this but if the contact form at https://www.govdata.de/Kontakt is used they will forward the question to the correct person or department.

**Comment by rouault** [comment]
>  from https://www.govdata.de/dl-de/by-2-0

I see this license mentioned in https://opendefinition.org/licenses/ as a "Other conformant licenses". It is not recommended for use by other entities than the German government, but OK.  It is exacly in the same category as the "Open Government Licence Canada 2.0" used by Canadian NTv2 grids that we do accept. So I think we can include this grid (at least for self consistency...)

**Comment by rouault** [comment]
That said, as far as I can see, this grid is not registered as a transformation from DHDN to ETRS89 in the EPSG dataset, which will make it not directly usable by PROJ, unless we create a dedicated entry for it in the meantime. Could someone try to reach to LGL or the relevant German authority so that they take an action item to register this grid with EPSG ?

**Comment by thbaumann** [comment]
> 
> 
> That said, as far as I can see, this grid is not registered as a transformation from DHDN to ETRS89 in the EPSG dataset, which will make it not directly usable by PROJ, unless we create a dedicated entry for it in the meantime. Could someone try to reach to LGL or the relevant German authority so that they take an action item to register this grid with EPSG ?

I can do this. Can you tell me who they have to contact and which information exactly they have to provide?

**Comment by rouault** [comment]
> Can you tell me who they have to contact and which information exactly they have to provide?

They should look at http://www.epsg.org/EPSGDataset/Makechangerequest.aspx which has instructions and submission forms

**Comment by rouault** [comment]
@m-kuhn  I've noticed very recently that producers of geodetic shift grids have interpreted differently the NTv2 specification regarding on the units for the channels that give accuracy
values. My findings is that some agencies have interpreted them as being values expressed in arc-seconds and others as metres...
The summary is there:
https://github.com/OSGeo/PROJ/wiki/Units-of-NTv2-accuracy-samples-%3F
Could you try to connect with LGL to check which interpretation (second vs metre) they have selected for BWTA2017.gsb ?

**Comment by m-kuhn** [comment]
Oh, embarassing. Thanks for the headsup.
@rdbath have you been in contact already and can you clarify this? I'm available if I can help something.

**Comment by thbaumann** [comment]
@m-kuhn: yes, I will forward this question, too

**Comment by thbaumann** [comment]
> That said, as far as I can see, this grid is not registered as a transformation from DHDN to ETRS89 in the EPSG dataset, which will make it not directly usable by PROJ, unless we create a dedicated entry for it in the meantime. Could someone try to reach to LGL or the relevant German authority so that they take an action item to register this grid with EPSG ?

Today I got the response from the LGL. They registered the grid now:

_"wir haben inzwischen das Formular ausgefüllt und mit zusätzlichen Informationen zu EPSG gesendet. 
Eine erste positive Rückmeldung von dort ist erfolgt.
Wir haben es aber nicht ins aktuelle Release geschafft, so dass es noch etwa 1 Monat dauern wird, bis unser BWTA2017 Gitter verfügbar sein wird:
We will review your request as quickly as possible. Please note that we will be issuing a new release of the EPSG Dataset later this week and unfortunately we did not receive your request until after our deadline for inclusion in that release. We anticipate the following release will be in about a month and if there are no problems the data should be included in that."_

**Comment by thbaumann** [comment]
> Could you try to connect with LGL to check which interpretation (second vs metre) they have selected for BWTA2017.gsb ?

@rouault / @m-kuhn:
We got now an answer from the LGL:
So the accuracy is NOT expressed in meters:

_Grundsätzlich haben wir uns bei der Erstellung des BWTA2017 an die Ntv2-Standards gehalten, d.h. sämtliche Angaben zu Shift- und Genauigkeitswerten in der Gitterdatei sind in Länge und Breite angegeben, wie auch im NTv2 Gitter BeTA2007. Allerdings haben wir uns im Gegenzug zur AdV entschieden, die Genauigkeitsangeben nicht auf 0.00 0.00 zu setzen, sondern diese automatisiert ermittelten Werte stehen zu lassen, da diese die sehr gute Qualität des NtV2–Gitters BWTA2017 unterstreichen._

_Näheres können Sie auch der Dokumentation zu BeTA2007: http://crs.bkg.bund.de/crseu/crs/descrtrans/BeTA/BETA2007dokumentationV15.pdf entnehmen._

**Comment by rouault** [comment]
> We got now an answer from the LGL:
> So the accuracy is NOT expressed in meters:

Thanks for the follow-up! Wiki page updated
