### ISSUE TITLE
Include Canada's NTv2.0 grid shift file

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/proj-datumgrid#26]
Initially discussed on http://lists.maptools.org/pipermail/proj/2018-September/008387.html

Canada's `NTV2_0.GSB` can now be freely downloaded from https://open.canada.ca/data/en/dataset/b3534942-31ea-59cf-bcc3-f8dc4875081a

This file is a binary grid shift file (.gsb format) to transform coordinates between the NAD27 and NAD83 reference systems and vice-versa. It has a higher resolution to `ntv1_can.dat`, which is included to proj-datumgrid under public domain.

The newer grid shift file is licensed under Canada's [Open Government Licence](https://open.canada.ca/en/open-government-licence-canada), which is nearly identical to UK's [Open Government Licence](http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/), which has:
> ... terms [that] are compatible with the Creative Commons Attribution License 4.0 and the Open Data Commons Attribution License, both of which license copyright and database rights.

It looks fine from my perspective to be included in this package. Does anyone else see differently?

I'd advise keeping the older grid shift file (ntv1_can.dat, 1.06 MB), and adding the 13.8 MB to the `north-america` directory. Should we rename it from `NTV2_0.GSB` to (e.g.) `ntv2_0.gsb`?

**Comment by sebastic** [comment]
The terms of the OGL - Canada look compatible with the DFSG & OSD. There is already code under that (and the UKs) license in Debian, so it seems to pass Debian FTP master scrutiny too.

The GSB should indeed be added to the `north-america` archive due to its size, but renaming it to use a lowercase filename is probably not a good idea. Init and other files are likely to reference the file as distributed, with its uppercase filename.

**Comment by mwtoews** [comment]
@sebastic thanks for reviewing the license compatibility! I'll assemble a PR with the unmodified file name.

**Comment by mwtoews** [comment]
I just noticed that there are several references to `ntv2_0.gsb` in PROJ:
 * [src/pj_datums.c](https://github.com/OSGeo/proj.4/blob/master/src/pj_datums.c#L49)
 * [nad/testntv2](https://github.com/OSGeo/proj.4/blob/master/nad/testntv2)
 * nad/CMakeLists.txt / nad/Makefile.am

The nad tests are only run if the lowercase file is present, but not the uppercase name. The references to `ntv2_0.gsb` were added by Frank on 2003-03-17 (from the ChangeLog). Should we reconsider renaming this grid shift file, so it can be used with older versions of PROJ?

**Comment by kbevers** [comment]
How about adding a few symbolic links with lower/mixed case names?

**Comment by mwtoews** [comment]
The simplest solution that I see is to rename this to a lowercase filename. Here's the rationale:

- Symbolic links are not supported by all operating systems, and when unzipping two files with upper/lowercase names on Windows 10, only one file is effectively extracted, so it's a bit messy/unclear.
- Only the lowercase name is used in PROJ since version 4.4.7 released 2003-03-31, over 15 years ago. This lower case name is embedded in the C source, makefiles, and documentation. The documentation also [used to indicate that the file be renamed to a lowercase name](https://github.com/mwtoews/proj.4/blob/e05dcd84ab69e1522c67c1ec9e5b38f45fd77c6e/docs/source/resource_files.rst#canada-ntv20). By using a lowercase name, no changes would be need to be made to either historic or current versions of PROJ.
- This file is from 1995 and [written for DOS](https://web.archive.org/web/20010227084518/http://cgis.geod.nrcan.gc.ca/products/html-public/GSDapps/English/NTv2_Fact_Sheet.html), which only use uppercase file names. However, doing some web searching, I can't find anyone referencing the uppercase name. Only lower or mixed case names are used by other software (a few examples are linked in #27), and these are predominantly from case-insensitive operating systems, besides a few exceptions (e.g. [Safe FME](https://docs.safe.com/fme/html/FME_Desktop_Documentation/FME_Desktop_Admin_Guide/FMEInstallation/Installing_Grid_Shift_Files.htm) or [ArcSDE](http://help.arcgis.com/en/geodatabase/10.0/sdk/arcsde/concepts/geometry/coordref/coordsys/geographic/usinggrid_gt.htm)).

Any objections to moving this file to a lower case filename?

**Comment by sebastic** [comment]
If most references to the file use the lowercase instead of uppercase as distributed, no objection from me.

**Comment by kbevers** [comment]
Convincing writeup! No objections from me either.

**Comment by mwtoews** [comment]
All PROJ versions since 4.4.7 use lowercase name.
