### ISSUE TITLE
Symbolic links to point to the latest version of the grids ?

### ISSUE THREAD

**Issue by rouault** [OSGeo/proj-datumgrid#37]
For my grid_packages table in proj.db, I currently point to URLs like 'https://download.osgeo.org/proj/proj-datumgrid-1.8.zip'.
This has the potential to rot quite quickly, and I think that pointing to the latest available version would generally be better.
A solution would to create and update symbolic links on https://download.osgeo.org/proj/ like
`ln -s proj-datumgrid-1.8.zip proj-datumgrid-latest.zip` each time we release a new package.

If you agree, I can offer the needed updates to HOWTORELEASE

The other possibility would be to update HOWTORELEASE to mention updating grid_alternatives.sql (but that might be too late if PROJ is released before the grid packages)

**Comment by kbevers** [comment]
> A solution would to create and update symbolic links on download.osgeo.org/proj like
ln -s proj-datumgrid-1.8.zip proj-datumgrid-latest.zip each time we release a new package.

Sounds reasonable to me.
