### ISSUE TITLE
Task for 2020 or later: include Swiss NTv2 grids

### ISSUE THREAD

**Issue by rouault** [OSGeo/proj-datumgrid#41]
Some exchanges with Swiss folks have shown that Swisstopo might release in (not earlier than) 2020 some of its datasets, including the NTv2 grids that do CH1903 to CH1903+ or ETRS89, which are currently downloadable as cost free but with some restrictions, under an open data license.

**Comment by ElmarBrockmann** [comment]
NTv2 data sets CHENYX06.gsb and CHENYX06_etrs.gsb added to proj-datungrid. 
Details see README.EUROPE.

**Comment by ElmarBrockmann** [comment]
Licence is Creative Commons CC0 1.0 Universal ->  https://www.swisstopo.admin.ch/en/knowledge-facts/surveying-geodesy/reference-frames/transformations-position.html and files can be download free of charge from web-shop.

**Comment by rouault** [comment]
Solved by #53
