### ISSUE TITLE
Confusing description for the direction of .gtx files

### ISSUE THREAD

**Issue by rouault** [OSGeo/proj-datumgrid#44]
README.EUROPE mentions for example "Denmark: GRS80 ellipsoidal heights -> DVR90 heights", but the content of the dvr90.gtx file is the value to add to a DVR90 height to get a GRS80 ellipsoidal height, so I think it would be less confusing to name it "Denmark: DVR90 heights -> GRS80 ellipsoidal heights".
The same applies for most of other .gtx file descriptions

**Comment by kbevers** [comment]
Yeah, that's correct (at least for DVR90). This stuff is always super confusing!

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/proj-datumgrid/pull/45
