### ISSUE TITLE
How to install datumgrid with new proj 6.0?

### ISSUE THREAD

**Issue by dirteat** [OSGeo/proj-datumgrid#47]
Hi there,
so nad2bin is not in proj 6.0 anymore, neither in datumgrid-1.8. Seems to be in datumgrid-world with a cmake which misses install directories. Would be nice if some clean-up and explanations could be provided somewhere!
Thanks,
Chris.

**Comment by sebastic** [comment]
What do you need `nad2bin` for?

`nad2bin` is built by [`CMakeLists.txt`](https://github.com/OSGeo/proj-datumgrid/blob/7dde892c14a53d85e59f9ba7822197c7bdb9cc2d/CMakeLists.txt#L15) in the project root, because it is required to build the proj-datumgrid archives.

**Comment by dirteat** [comment]
Building latest grass with new libproj...

```
found PROJ version 6.0.0
using new PROJ version 5+ API
checking for location of External PROJ library... 
checking for proj_pj_info in -lproj... yes
checking for location of External PROJ data files... /usr/share/proj
checking for /usr/share/proj/epsg... no
configure: warning: *** Unable to locate PROJ data files.
checking for nad2bin... no
configure: error: *** Unable to locate nad2bin (needs to be in PATH).
error: Bad exit status from /home/iurt/rpmbuild/tmp/rpm-tmp.yHo9CE (%build)
```

**Comment by sebastic** [comment]
That looks like an issue in GRASS.

The GRASS buildsystem checks for `nad2bin`, but doesn't appear to use it. Their `configure.in` should be updated to not require its presence.

**Comment by neteler** [comment]
We'll remove that nad2bin check in GRASS GIS which is superfluous.

**Comment by neteler** [comment]
Done:

https://trac.osgeo.org/grass/changeset/74181
        grass/branches/releasebranch_7_4/   --> It will go into GRASS GIS 7.4.5

https://trac.osgeo.org/grass/changeset/74180
        grass/branches/releasebranch_7_6/   --> It will go into GRASS GIS 7.6.1

https://trac.osgeo.org/grass/changeset/74179
        grass/trunk/    --> It will go into GRASS GIS 7.8.0

To start today, update from the release branch of interest.

Thanks for the notification.

**Comment by sebastic** [comment]
@neteler, grepping through the GRASS 7.6.0 sources shows `nad2bin` mentioned in:

 * `binaryInstall.src`
 * `configure`
 * `configure.in`
 * `include/Make/Platform.make.in`
 * `macosx/app/Makefile`
 * `macosx/ReadMe.rtf`

**Comment by neteler** [comment]
@sebastic already fixed except for macosx as that's not my playground.

**Comment by dirteat** [comment]
Thank you for the feedback and the help!

Also, the statement that datumgrid should be unpacked within data/  of proj is confusing. Unpacking datumgrid produces a directory proj-datumgrid-XX/ 
Does this directory should be put inside data/, or the content of that directory should be moved to data/.
The second case is problematic, there are conflicting files, the cmake and CMakeList.txt for instance. What should we do with them?

Concerning grass, nad2bin is not the only issue. It is also looking for /usr/share/proj/epsg but it looks to me that these files are not produced anymore?

**Comment by sebastic** [comment]
There is no top-level directory (when using the tarball):
```
$ wget http://download.osgeo.org/proj/proj-datumgrid-1.8.tar.gz -P /tmp/
$ tar tavf /tmp/proj-datumgrid-1.8.tar.gz 
-rw-r--r-- kevers/staff 1053928 2018-09-15 15:56 alaska
-rw-r--r-- kevers/staff 4153000 2018-02-26 19:39 egm96_15.gtx
-rw-r--r-- kevers/staff  277424 2018-02-21 19:28 ntf_r93.gsb
-rw-r--r-- kevers/staff  264424 2018-09-15 15:56 conus
-rw-r--r-- kevers/staff    7048 2018-09-15 15:56 stpaul
-rw-r--r-- kevers/staff   83696 2018-02-21 19:28 BETA2007.gsb
-rw-r--r-- kevers/staff   26728 2018-09-15 15:56 prvi
-rw-r--r-- kevers/staff    4645 2018-09-10 20:13 README.DATUMGRID
-rw-r--r-- kevers/staff    8872 2018-09-15 15:56 FL
-rw-r--r-- kevers/staff  318464 2018-02-21 19:28 nzgd2kgrid0005.gsb
-rw-r--r-- kevers/staff     232 2018-09-15 15:56 null
-rw-r--r-- kevers/staff 1113184 2018-02-21 19:28 ntv1_can.dat
-rw-r--r-- kevers/staff    3560 2018-09-15 15:56 MD
-rw-r--r-- kevers/staff  452008 2018-09-15 15:56 hawaii
-rw-r--r-- kevers/staff   59208 2018-09-15 15:56 stgeorge
-rw-r--r-- kevers/staff   26728 2018-09-15 15:56 stlrnc
-rw-r--r-- kevers/staff    6760 2018-09-15 15:56 WI
-rw-r--r-- kevers/staff    4424 2018-09-15 15:56 TN
-rw-r--r-- kevers/staff   11112 2018-09-15 15:56 WO
```

Unpacking this into the `data/` directory is sufficient, e.g.:
```
$ tar xavf /tmp/proj-datumgrid-1.8.tar.gz -C data/
```

There are also no conflicting files in the tarball, those are [excluded in the build process](https://github.com/OSGeo/proj-datumgrid/blob/1.8/CMakeLists.txt#L40).

There is no GRASS release with support for PROJ 6.0.0 yet, so you will likely run into more issues trying to build GRASS releases with PROJ 6.0.0. Changes for PROJ 6 where only committed recently, see:

 [[GRASS-dev] GRASS GIS + PROJ 6 + GDAL 2.5](https://lists.osgeo.org/pipermail/grass-dev/2019-March/091539.html)

Note the SVN revision required to handle the absence of the `epsg` file.

**Comment by mwtoews** [comment]
Just to note, there is also no top-level directory for the .zip equivalent, so Info-ZIP's `unzip` works:
```
cd $PROJ_LIB
unzip proj-datumgrid-1.8.zip
```

Other unzip utilities behave differently. For example, on a Windows 10 Desktop, the "Extract all" method defaults to extracting files in a sub-folder named "proj-datumgrid-1.8"... but I think it's up to the user to ensure the files are extracted to the correct directory.

**Comment by dirteat** [comment]
Thanks, that is because I downloaded the tar ball from the "release" github directory:

https://github.com/OSGeo/proj-datumgrid/releases/

I though releases were supposed to be there. The tarballs in there are all with a top directory and conflicting files.

**Comment by kbevers** [comment]
> I though releases were supposed to be there. The tarballs in there are all with a top directory and conflicting files.

No, those are just auto-generated by GitHub. As far as I know they can't be turned off, but it is possible to add the correct archives. I do this already for the PROJ repository and probably should do that here as well. It will take me some time to go through all the releases but I will put it on my todo-list.

**Comment by dirteat** [comment]
Ok, that works, thanks to all. Proj6 and grass-7.6 landing in Mageia Cauldron now. I am closing.
