### ISSUE TITLE
Portugal (Continental) - *.gsb files

### ISSUE THREAD

**Issue by lusitanica** [OSGeo/proj-datumgrid#51]
It would be nice to include in this repository two NTv2.0 grid shift files available for download from the Portuguese National Geodetic Authority (DGTerritorio) web site, and published under Creative Commons - Attribution 4.0 International. 

I have all the relevant information, grids included, in the following GitHub repository:

https://github.com/lmikegeo/ntv2-pt

**Comment by kbevers** [comment]
Awesome. Please create a pull request with the grids. Start here: https://github.com/OSGeo/proj-datumgrid/blob/master/CONTRIBUTING.md

**Comment by lusitanica** [comment]
Looking at the file **grid_transformation.sql**  I've found on lines 193 and 194, the files I intended to commit, referenced. DLx_ETRS89_geo.gsb and D73_ETRS89_geo.gsb, respectively. Just to be sure they weren't committed before. I can see a branch named Europe-1.3 ...

**Comment by kbevers** [comment]
They are just that, references. We don't supply all grids that are registered in our database, but we can use them if they are available on a users system. You can safely create a PR with these two grids.

There is no europe-1.3 branch. There is a git tag however, this is just to keep track of versions of the packages, you can ignore that.

**Comment by gioman** [comment]
see https://github.com/OSGeo/proj-datumgrid/pull/54

**Comment by PedroVenancio** [comment]
https://github.com/OSGeo/proj-datumgrid/commit/46e538feb7ce906e6cf1deb4efbd96443d72d287

This issue can be closed now.

**Comment by rouault** [comment]
@lusitanica I've noticed very recently that producers of geodetic shift grids have interpreted differently the NTv2  specification regarding on the units for the channels that give accuracy 
values.  My findings is that some agencies have interpreted them as being values expressed in arc-seconds and others as metres...
The summary is there:
https://github.com/OSGeo/PROJ/wiki/Units-of-NTv2-accuracy-samples-%3F
Could you try to connect with DGTerritorio to check which interpretation (second vs metre) they have selected ?

**Comment by PedroVenancio** [comment]
Hi @rouault 

I will try to confirm with DGT.
