### ISSUE TITLE
GEOID18 vertical grids for NAVD88 <--> NAD83 available

### ISSUE THREAD

**Issue by rouault** [OSGeo/proj-datumgrid#55]
https://geodesy.noaa.gov/GEOID/GEOID18/downloads.shtml

**Comment by elil** [comment]
These files should maybe be reviewed due to errors in the earliest distributed little endian files.  

> ******Urgent: Critical Change to GEOID18 grid files********
>
>NGS has corrected errors in some of the GEOID18 grid files posted on the GEOID18 Downloads webpage prior to November 26, 2019. See below for more information and details:
>Critical Change
>
>The GEOID18 grid files in the little endian and ASCII grid formats that were posted on the NGS website prior to November 26, 2019, contained errors in a small percentage of the grid cells (1 in 500). NGS has since corrected the errors and replaced these files on the GEOID18 download page. We encourage users that have previously downloaded those grids to immediately replace them with the updated grids.
>Unaffected Products
>
>The GEOID18 model itself, the big endian file format, and all of the NGS tools and services that incorporate GEOID18, including the Online Positioning User Service (OPUS), remain unaffected and may continue to be used.

See also, https://www.ngs.noaa.gov/GEOID/GEOID18/, https://www.ngs.noaa.gov/GEOID/GEOID18/downloads.shtml, https://geodesy.noaa.gov/GEOID/GEOID18/geoid18_tech_details.shtml

**Comment by rouault** [comment]
> These files should maybe be reviewed due to errors in the earliest distributed little endian files.

@elil Thanks for the notice. Addressed per https://github.com/OSGeo/proj-datumgrid/pull/86
