### ISSUE TITLE
Divide the grids into several packages in the future

### ISSUE THREAD

**Issue by kbevers** [OSGeo/proj-datumgrid#7]
The recently included grids from Australia are quite big (80MB). Over time the grid collection will be larger and larger making the datum grid package unnecessarily big for most users. We should consider dividing the grids into several packages, for instance differentiating between horizontal and vertical grids. This could be subdivided even further in regional packages if necessary. 

At first I think it makes sense to have two packages:

1. `proj-horizontal-datumgrids-1.7.0.tar.gz`
2. `proj-vertical-datumgrids-1.70.0.tar.gz`

Which eventually can be divided into

1a. `proj-horizontal-datumgrids-europe-1.70.0.tar.gz`
1b. `proj-horizontal-datumgrids-northamerica-1.70.0.tar.gz`
1c. `...`
2a. `proj-vertical-datumgrids-europe-1.70.0.tar.gz`
2b. `proj-vertical-datumgrids-northamerica-1.70.0.tar.gz`
2c. `...`

At some point it could also be necessary to create a package of deformation/velocity model grids, but so far not many of those exists.

**Comment by sebastic** [comment]
I think it makes sense to have these subset packages **in addition** to the proj-datumgrid archive that contains everything.

Distribution packages will keep using everything most likely anyway, but it gives users who build their own proj the option to use a subset of grids relevant for their use.

**Comment by kbevers** [comment]
That works for me.

Changes to the CMakefiles should be made so that all packages can be created more or less automatically.

**Comment by sebastic** [comment]
The first step has been taken, the Australian grids are split off into their own archive. (#17)

I'm not sure if it makes sense to separate horizontal & vertical grids. If I look at the (non-free) Dutch grids, its `rdtrans2008.gsb` & `naptrans2008.gtx` go hand-in-hand, separating them doesn't make sense. I think the same goes for many if not all other national grids.

Providing separate `proj-datumgrid` archives for various regions as we've started to do for the Australian grids (in `proj-datumgrid-oceania`) will probably remain good enough.

**Comment by kbevers** [comment]
> I'm not sure if it makes sense to separate horizontal & vertical grids. If I look at the (non-free) Dutch grids, its rdtrans2008.gsb & naptrans2008.gtx go hand-in-hand, separating them doesn't make sense. I think the same goes for many if not all other national grids.

I agree. It is better to keep them together.

> Providing separate proj-datumgrid archives for various regions as we've started to do for the Australian grids (in proj-datumgrid-oceania) will probably remain good enough.

I hope so. I have just mentioned it on the mailing list. I reckon someone will speak up if it is completely unacceptable to them. I'll set up `-europe` and `-northamerica` packages tomorrow afternoon or evening.

**Comment by kbevers** [comment]
Continueing discussion from #19 

> That would also reduce the need to mark the package for each grid, just documenting the package for the each region should suffice.

Yes, that was what sparked the idea in the first place.

> Where to find the region README files /or hyperlinking them is probably good. And/Or mentioning the directory where the region grids live.

Good suggestion. I can link directly to the files on GitHub and also mention that the individual archives can be grabbed from http://download.osgeo.org/proj/.

**Comment by kbevers** [comment]
Additionally I am going to include a couple of init-files that are related to the some of the grids in the regional packages. This will be a first small step towards separating PROJ resources from the PROJ source distribution.

**Comment by sebastic** [comment]
For regional packages the typical installation procedure will be to unpack the content of the archive into `/usr/share/proj`, that doesn't need any special handling.

If the core package is going to contain init files these need to be added to the build system in proj as well (like the recent [.gtx change](https://github.com/OSGeo/proj.4/pull/813)) to have those init files installed along with proj and the grid files (when the content of the datumgrid archive is unpacked into the `nad` directory of the proj source).

**Comment by kbevers** [comment]
> For regional packages the typical installation procedure will be to unpack the content of the archive into /usr/share/proj, that doesn't need any special handling.

This will be the case for now. I'm adding init files and grids from https://github.com/NordicGeodesy/NordicTransformations. They fit in rather nicely in this setup and is at the same time a nice demo of new features in PROJ.

Eventually it would be nice to get rid of `nad/` all together but that is a project some time in the future.

**Comment by kbevers** [comment]
Closed with #20
