### ISSUE TITLE
filelist.csv not updated with Iceland grids

### ISSUE THREAD

**Issue by rouault** [OSGeo/proj-datumgrid#93]
@dalia2 Just to make sure if it is in your action items

**Comment by dalia2** [comment]
I added grids under branch:add-grids-for-Iceland/proj-datumgrid/filelist.csv , lines 201-206
https://github.com/dalia2/proj-datumgrid/blob/add-grids-for-Iceland/filelist.csv

**Comment by rouault** [comment]
Can you make a pull request with that ?

**Comment by dalia2** [comment]
I have opened pull request, can you take the filelist.csv file?

**Comment by kbevers** [comment]
@dalia2 it looks like it would be easier for you to make a new branch from master and commit the filelist.csv to that new branch. Then submit a new pull request.

**Comment by dalia2** [comment]
I tried to make new branch update_filelist2 from master, but with new branch I can not get filelist.csv, this file is missing. In previous branch add-grids-for-Iceland I have filelist.csv file, that mean at that time on that version of OSGeo/proj-datumgrid the filelist.csv existed. Not sure what went wrong. The only solution what I see, I need to update (syncing) my proj-datumgrid fork with current newer version of master OSGeo/proj-datumgrid using this approach https://digitaldrummerj.me/git-syncing-fork-with-original-repo/  I will try to do that tomorrow.

**Comment by rouault** [comment]
What I can advise:
- create a backup of your filelist.csv
- git fetch origin (or whetever origin name you have chosen to point to https://github.com/OSGeo/proj-datumgrid)
- git checkout master
- git reset --hard origin/master
- git checkout -b add_iceland_grids_to_filelist
- manually merge your backup of filelist.csv

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/proj-datumgrid/pull/95
